### ISSUE TITLE
How to submit authentication ? 

### ISSUE THREAD

**Issue by unl1k3ly** [aeirola/slack-irc-client#17]
Nick auth does goes on 'what do I do' as well ?

**Comment by hanakin** [comment]
not sure what your saying but believe its related so 

How do we identify our account? This is a common practice to account for team members in an irc channel where your are required to identify using the following command to grant you OP

`/msg NickServ IDENTIFY *******`

where the ***** are your password

it appears there is no setting for your password/identity?

**Comment by iMartyn** [comment]
https://github.com/aeirola/slack-irc-client/pull/25 will solve this one :-)

**Comment by aeirola** [comment]
Yeah, closed by #25
