### ISSUE TITLE
Slack username is used instead of userName

### ISSUE THREAD

**Issue by augustjanse** [aeirola/slack-irc-client#19]
Hi! I set this up just now, following the instructions mostly*. It all seems to work as expected, except that my Slack username is used instead of the username supplied in the userName variable. Exact string in my "about me" field:

    { "server": "dreamhack.se.quakenet.org", "userName": "Juniorus123" }

I deliberately changed it into something that probably isn't taken. When I changed my Slack username and restarted, the new Slack username was used, although that workaround has its limitations.

*: Didn't remove #general since it can't be deleted or left. Didn't supply port. On a Windows 10 machine.

**Comment by aeirola** [comment]
Ah, so the `userName` configuration field is used to set the real name (https://tools.ietf.org/html/rfc2812#section-3.1.3) of the user, not the nickname. The naming convention comes from the node-irc [configuration object](http://node-irc.readthedocs.io/en/latest/API.html?highlight=userName#irc.Client). The IRC nickname is always set to the Slack username.

P.S. you should be able to remove the #general channel by setting the default channel to something else. Or has this maybe changed at some point?

**Comment by augustjanse** [comment]
Right, didn't get that. Thanks!

The settings say "Choose the channels new members will automatically be added to (in addition to #general).", so it doesn't look like it can be changed.
