### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by aeirola** [aeirola/slack-irc-client#33]
Hello everyone,

I wrote this software many years ago while my world was going through the transition from IRC to more modern communication services such as Slack. Now that transition has completed for me, meaning that I haven't logged in to IRC in ages, and thus not used this piece of software either.

Unfortunately, this also means that I don't have enough motivation to keep maintaining this repository with the care it needs. This was last seen in version 0.3.1 introducing the bug described in #32. I don't feel confident in making changes to the software without properly testing them first, and without being an active IRC user, it is hard to test the changes.

Thus, I'm looking for someone who would still be an active IRC user, and be able to take better care of the project. There isn't much in ways of feature development needed for the service, but some small fixes will probably have to be handled once in a while.

If you feel like you would be able to help out here, please don't hesitate to come forward.

Thanks, Axel

**Comment by di** [comment]
@aeirola I'd be happy to be a maintainer, I use this software daily and would be able to review PRs, respond to issues, make and test new releases, etc.

**Comment by aeirola** [comment]
@di Cool! Really nice to hear that there are still eager users of the software. I will give you collaborator access to the repo for now, so that you can push to master and make commits by tagging releases. Travis should do the rest of the work of publishing the package to NPM.

Thanks again for helping out.

**Comment by di** [comment]
Thanks @aeirola.

Just so I'm sure I understand the release process, currently you:
* push a commit bumping the version to master
* tag a new release at that commit
* push the tag
* and the Travis build does the rest

Is that correct?

**Comment by aeirola** [comment]
Yeah, most easily done with the following commands

```bash
npm version patch
git push --follow-tags
```

**Comment by di** [comment]
@aeirola I made a release (https://github.com/aeirola/slack-irc-client/releases/tag/v0.3.3) but it doesn't look like this got deployed to NPM, any idea what went wrong?

**Comment by aeirola** [comment]
Yeah, sorry about that. Seems like my 2FA settings on NPM blocked the Travis package upload. I updated my settings and rerun the job https://travis-ci.org/aeirola/slack-irc-client/jobs/336689676. Now version 0.3.3 seems to be available on NPM. This shouldn't be a problem in the future.

**Comment by daniela-waranie** [comment]
@di thanks for becoming a maintainer 2 years ago. Is there a chance to see you working on open issues (https://github.com/aeirola/slack-irc-client/issues) or is this project unmaintained again?

**Comment by di** [comment]
@daniela-waranie I still use this daily and it works great for me, and there hasn't been any new issues reported since I became a maintainer.

I don't have the bandwidth to go back and attempt to fix all the old issues reported but I'm still happy to review PRs and make releases.

Is there something in particular that is affecting you or that you're thinking of working on?
