### ISSUE TITLE
Where do I find the user API token?

### ISSUE THREAD

**Issue by Kabouik** [aeirola/slack-irc-client#4]
Hi,

I'm sorry if the answer is trivial, but I have a question about this step of your how-to:

>Get user API token for your team at https://api.slack.com/web#authentication

Seems this page has changed, as someone has also noted it [here](https://github.com/shahruz/Send-to-Slack/issues/5). I am only able to create a test token, and it seems to work with this, but is this what we are supposed to use?

**Comment by aeirola** [comment]
Yeah, it currently depends on using the test tokens available from the Slack web API web page. Thanks for letting me know that the instructions are outdated. I'l update the documentation to reflect the change. 

I suppose the correct way would be to setup some service or web page where the user could generate a Slack token specifically for slack-irc-client. I would have to look into this and see if it is feasible.

**Comment by aeirola** [comment]
I created a quick service to generate proper Slack tokens for slack-irc-client usage. You can try it out at http://aeirola.github.io/slack-irc-client/. I'll update the documentation once I have time to test the generated tokens properly.

**Comment by aeirola** [comment]
Seems to work fine, updated the readme to point to the token generation service.
